# Step 1: Modules caching
FROM golang:1.22-alpine as modules
COPY go.mod go.sum /modules/
WORKDIR /modules
RUN apk add --no-cache git
RUN go mod download

# Step 2: Builder
FROM golang:1.22-alpine as builder
ARG TARGETOS
ARG TARGETARCH
COPY --from=modules /go/pkg /go/pkg
COPY . /app
WORKDIR /app
COPY --from=modules /modules/go.sum /app/go.sum
RUN apk add --no-cache git && go mod tidy
RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH \
    go build -o /bin/app ./cmd/web

# Step 3: Final
FROM scratch

ENV USER=app
ENV GLOG_logtostderr=1

EXPOSE 8888

# GOPATH for scratch images is /
COPY --from=builder /app/cmd/web/app/ /
COPY --from=builder /bin/app /app
CMD ["/app"]