# Step 1: Modules caching
FROM golang:1.22-alpine as modules
COPY go.mod go.sum /modules/
WORKDIR /modules
RUN apk add --no-cache git
RUN go mod download

# Step 2: Builder
FROM golang:1.22-alpine as builder
COPY --from=modules /go/pkg /go/pkg
COPY . /app
WORKDIR /app
COPY --from=modules /modules/go.sum /app/go.sum
RUN apk add --no-cache git && go mod tidy
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -tags migrate -o /bin/app ./cmd/counter

# Step 3: Final
FROM scratch

ENV USER=app

EXPOSE 5002

# GOPATH for scratch images is /
COPY --from=builder /app/cmd/counter/config.yml /
COPY --from=builder /app/db/migrations /db/migrations
COPY --from=builder /bin/app /app
CMD ["/app"]